apiVersion: apps/v1
kind: Deployment
metadata:
  name: learnopia-frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: learnopia-frontend
  template:
    metadata:
      labels:
        app: learnopia-frontend
    spec:
      containers:
        - name: learnopia-frontend
          image: darshib/learnopia:learnopia-frontend
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: learnopia-frontend-service
spec:
  selector:
    app: learnopia-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
