apiVersion: apps/v1
kind: Deployment
metadata:
  name: enrollment-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: enrollment
  template:
    metadata:
      labels:
        app: enrollment
    spec:
      containers:
        - name: enrollment
          image: darshib/learnopia:learnopia-service4
          ports:
            - containerPort: 8030