name: cicd-workflow to create docker image and upload into AWS ECR

on:
  push:
    branches: [ "development" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Setup AWS ECR Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Install dependencies for all services (optional)
      run: |
        for service in authenticate course content enrollment payment; do
          if [ -f services/$service/package.json ]; then
            echo "Installing dependencies for $service..."
            cd services/$service
            npm install
            cd -
          fi
        done
        - name: Build and Push Docker images to ECR
          env:
            ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
            IMAGE_TAG: ${{ github.sha }}
            LATEST_TAG: latest
            ECR_REPO_PREFIX: learnopia
          run: |
            for service in authenticate course content enrollment payment; do
              IMAGE_NAME="$ECR_REGISTRY/$ECR_REPO_PREFIX/$service:$IMAGE_TAG"
              LATEST_IMAGE_NAME="$ECR_REGISTRY/$ECR_REPO_PREFIX/$service:$LATEST_TAG"
              
              echo "Building and pushing $IMAGE_NAME and $LATEST_IMAGE_NAME"
              
              # Build the image
              docker build -t $IMAGE_NAME -t $LATEST_IMAGE_NAME services/$service
              
              # Push both the commit hash tag and the latest tag
              docker push $IMAGE_NAME
              docker push $LATEST_IMAGE_NAME
            done

